### ISSUE TITLE
arbiter Trusts polyswarmd and the Connection Between the Two Components

### ISSUE THREAD

**Issue by myhndl** [polyswarm/arbiter#5]
arbiter implicitly trusts polyswarmd, which can result in compromise of NCT, ETH or any other token.

arbiter must not trust polyswarmd nor the connection between them. Until this trust is eliminated, arbiter can only safely be run co-privileged to polyswarmd and cannot have its communications traverse an untrusted link.

Threat models:

compromise of the communications channel between arbiter and polyswarmd will allow an attacker to forge transactions that are happily signed by arbiter, including funds-draining transactions: https://gitlab.polyswarm.io/polyswarm/arbiter/blob/4f9acf781f6462ebbcf65c54998976c9cdfff323/arbiter.py#L48

compromise of polyswarmd enables the same without any network shenanigans

Acceptance criteria:

 arbiter verifies that all signature-requested transactions from polyswarmd to arbiter correspond to a desired action.

**Comment by Rizato** [comment]
I added some measure of protection at https://github.com/polyswarm/arbiter/blob/master/src/arbiter/__init__.py#L169

It does not validate addrs yet.

**Comment by myhndl** [comment]
Addressed or is being tracked in `polyswarm-client`
